### DISCUSSION TITLE
Support for mTLS (client certificates)

### DISCUSSION THREAD

**Discussion by YevPo** [basecamp/kamal-proxy#120] [Ideas and Issue Triage]
Hello, kamal team!

Are there any plans to implement support for mTLS for kamal-proxy and kamal?

Right now, we use traefik accessory for that, but it will be nice to just use kamal. 

Relevant Links:
https://doc.traefik.io/traefik/https/tls/#client-authentication-mtls
https://doc.traefik.io/traefik/middlewares/http/passtlsclientcert/#passtlsclientcert

**Comment by lumpidu** [comment]
I am also intereseted in that, can you elaborate on how you are using traefik in combination with kamal for this purpose ?

**Reply by YevPo** [reply]
@lumpidu , here is a full configuration.

1) Traefik is setup as a kamal accessory, it is described in kamal upgrade guide - https://kamal-deploy.org/docs/upgrading/continuing-to-use-traefik/
2) Traefik is used for both server and client certs, so `ssl` for kamal-proxy should be disabled.
3) For this to work, you need to put corresponding certificates in /etc/ssl/client and /etc/ssl/server dirs on servers. It can be done via ansible or some other automation(maybe even via kamal pre-deploy hook script):
- /etc/ssl/server/cert_file.pem
- /etc/ssl/server/cert_key_file.key
- /etc/ssl/client/mtls_ca.crt

Those are just examples, files can be named differently and stored in different dirs.

4) If I remember correctly, both traefik and kamal-proxy need to be rebooted after all this configuration is set.

5) We use "passtlsclientcert" traefik option. I.e. traefik checks mtls cert and passes a header with result to the app. Then app decides what to do with the result. This is useful when only come clients require mtls. Traefik supports stricter options aswell.

See next docs for details:
Traefik:
https://doc.traefik.io/traefik/https/tls/
https://doc.traefik.io/traefik/https/tls/#client-authentication-mtls
https://doc.traefik.io/traefik/middlewares/http/passtlsclientcert/
Kamal:
https://kamal-deploy.org/docs/upgrading/continuing-to-use-traefik/
https://kamal-deploy.org/docs/configuration/accessories/

## Config Examples

### .kamal/hooks/pre-proxy-reboot
Pre proxy reboot hook looks like this(.kamal/hooks/pre-proxy-reboot):
```
#!/bin/sh
kamal proxy boot_config set \
  -c ./config/deploy.yml \
  --publish false \
  --docker_options label=traefik.http.routers.kamal_proxy.rule=PathPrefix\(\`/\`\) \
                   label=traefik.http.services.kamal_proxy.loadbalancer.server.port=80 \
                   label=traefik.http.routers.kamal_proxy.entrypoints=websecure \
                   label=traefik.http.routers.kamal_proxy.tls=true \
                   label=traefik.http.routers.kamal_proxy.middlewares=mtls-middleware,compress-middleware
```

###  ./config/deploy.yml
In kamal deploy file, SSL for kamal-proxy should be disabled, because traefik handles SSL:
```
proxy:
  ssl: false
```

Traefik accessory in kamal deploy file looks like this:
```
accessories:
  traefik:
    service: traefik
    image: traefik:v2.11
    port: 443
    files:
      - ./traefik/traefik_config.yml:/etc/traefik/traefik_config.yml # i.e. traefik_config is stored in version control and then copied on host by kamal during deploy.
    cmd: |
      --providers.docker \
      --accesslog=true \
      --accesslog.format=json \
      --entryPoints.web.address=:80 \
      --entryPoints.websecure.address=:443 \
      --entryPoints.web.http.redirections.entryPoint.to=websecure \
      --entryPoints.web.http.redirections.entryPoint.scheme=https \
      --entryPoints.web.http.redirections.entrypoint.permanent=true \
      --providers.file.filename=/etc/traefik/traefik_config.yml
    options:
      volume:
        - "/etc/ssl/client:/etc/ssl/client" # For MTLS CA cert chain
        - "/etc/ssl/server:/etc/ssl/server" # For regular server certs
        - "/var/run/docker.sock:/var/run/docker.sock"
    roles:
      - web
    labels:
      traefik.http.middlewares.mtls-middleware.passtlsclientcert.info.subject.commonName: true
      traefik.http.middlewares.compress-middleware.compress: true
```

###  ./traefik/traefik_config.yml
And `./traefik/traefik_config.yml` looks like this:
```
tls:
  certificates:
    - certFile: /etc/ssl/server/cert_file.pem
      keyFile: /etc/ssl/server/cert_key_file.key
  options:
    default:
      clientAuth:
        caFiles:
          - /etc/ssl/client/mtls_ca.crt
        clientAuthType: VerifyClientCertIfGiven
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```
