### DISCUSSION TITLE
Allow loadbalancer to communicate with the proxies private networks

### DISCUSSION THREAD

**Discussion by mhenrixon** [basecamp/kamal-proxy#138] [Ideas and Issue Triage]
So in the below example, I can rewrite the environment variables, tell Kamal that it should ask the database for a connection on the private IP, and set up `pg_hba.conf` to allow connections on `10.0.0.0/16` for a private connection.

I wanted to know if there is a way to use the public IP for SSH connection, but tell the load balancer to communicate with the proxies on the private IP instead. 

The problem is that it is otherwise very hard to sort out having the load balancer on the same instance as one of the proxies, and it turned out to be pretty hard to make that one proxy do load balancing for all hosts except itself.

```yaml
env:
  clear:
    DATA_DB_HOST: 10.0.0.240
    DATA_DB_NAME: dat
    DATA_DB_PORT: 5432
    MEMCACHE_SERVERS: 10.0.0.244:11211
    production: production
    RAILS_MAX_THREADS: 3
    RAILS_MIN_THREADS: 3
    RAILS_SERVE_STATIC_FILES: true
    REDIS_URL: redis://10.0.0.230:6379
    RUBY_YJIT_ENABLE: 1
    WEB_CONCURRENCY: 3
  secret:
  - SECRET_KEY_BASE
  - DATA_DB_PASS:POSTGRES_PASSWORD
  - DATA_DB_USER:POSTGRES_USER

servers:
  web:
    hosts:
    - 143.54.5.1
    - 143.54.5.2
  job:
    hosts:
    - 143.54.5.10
    cmd: bin/sidekiq
    env:
      clear:
        JOBS_THREADS: 10

accessories:
  db:
    image: postgres:17.4-alpine
    cmd: postgres -c config_file=/etc/postgresql/postgresql.pre.conf -c hba_file=/etc/postgresql/pg_hba.pre.conf
    directories:
    - /data/postgres/primary:/var/lib/postgresql/data
    env:
      secret:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    files:
    - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
    - config/postgres/pg_hba.pre.conf:/etc/postgresql/pg_hba.pre.conf
    - config/postgres/postgresql.pre.conf:/etc/postgresql/postgresql.pre.conf
    host: 143.54.5.12
    port: 10.0.0.240:5432:5432

  redis:
    image: redis:7.2-alpine
    cmd: redis-server --appendonly yes --appendfsync everysec --save 900 1 300 10 60 1000 --dir /data
    directories:
    - /data/redis:/data
    host: 143.54.5.12
    port: 10.0.0.230:5432:5432
```
