### DISCUSSION TITLE
Any plans to suppport HTTP3?

### DISCUSSION THREAD

**Discussion by hugopl** [basecamp/kamal-proxy#146] [Q&A] [answered]
Hi,

First, great tool, thanks a lot for open source it ❤️.

I see that kamal-proxy supports http2, is there any plans to add support for http3?

**Comment by kevinmcconnell** [comment]
Hi @hugopl,

Yes, http/3 is definitely something we should have. It's been on my list to do it, and I should be able to get it shipped soon (probably a couple weeks, as I'm on vacation). Thanks for the reminder!

**Comment by kevinmcconnell** [comment]
Tracking this in #147.

**Comment by kevinmcconnell** [comment, marked as answer]
HTTP/3 is supported on `main` now, and will be in the next release.

**Comment by hugopl** [comment]
How to enable it through `kamal` deploy config?

I tried:
```
proxy:
  http3: true
```
and
```
proxy:
   ssl: true
   run:
    options:
       command: ["--http3"]  # Pass --http3 flag directly
```
neither work, I also didn't find any documentation. I'm using kamal-proxy 0.9.2 and kamal 2.10.1.
