### DISCUSSION TITLE
Kamal Proxy logs: "level":"INFO","msg":"http: TLS handshake error from <myip>:: no server name provided"

### DISCUSSION THREAD

**Discussion by orbanbotond** [basecamp/kamal-proxy#58] [Q&A]
Hi Guys,

I have this `deploy.yml` file:

```
# Deploy to these servers.
servers:
  - <ip of the cloud server>

proxy: 
  ssl: true
  host: <ip of the cloud server, same as above>
  app_port: 3000
```

Then as I turned the ssl to true, the web app no longer responds, I checked the `kamal proxy log`:
"level":"INFO","msg":"http: TLS handshake error from <my home ip>:47524: no server name provided"

Any solutions?
thx in advance
