### DISCUSSION TITLE
Routing to wildcard subdomains not working

### DISCUSSION THREAD

**Discussion by naveencom** [basecamp/kamal-proxy#72] [Q&A]
My kamal config:

```
proxy:
  ssl: true
  host: example.com
  app_port: 8000
  healthcheck:
    interval: 10
    path: /up
    timeout: 5
```
Cloudflare encryption mode: Full (strict)

![cloudflare-settings](https://github.com/user-attachments/assets/04015549-a769-4e23-ac83-740cffaa7d15)

Then I obtained and deployed an [Origin CA certificates](https://developers.cloudflare.com/ssl/origin-configuration/origin-ca/) from Cloudflare.

`
docker exec kamal-proxy kamal-proxy deploy service-web --target="*.example.com" --host="example.com" --tls --tls-certificate-path /etc/ssl/certs/example.com.pem --tls-private-key-path /etc/ssl/certs/example.com.key`

When I run the above command, I'm getting the following error.
`Error: *.example.com :invalid host pattern `

example.com is accessible, but not subdomain.example.com

I've gone through these discussions #30 & #45 

I'm a newbie so I don't know if I've made any mistakes.

Please help me.
