### DISCUSSION TITLE
Best way to route to a kamal deployed target from another service

### DISCUSSION THREAD

**Discussion by frenkel** [basecamp/kamal-proxy#87] [Q&A]
I have a service running that is deployed by kamal and want to add a different service with some custom certificates that points to that same application. You can't use a service as target, so you would need to update the name of the kamal deployed container in the manually deployed service. As a work around I've added a network alias in my kamal config, something like so:
```
servers:
  web:
    hosts:
      - example.com
    options:
      network-alias: unchanging-name-for-web
```
and now I can add the extra service with `unchanging-name-for-web` as target. However, I think during a Kamal deploy some requests might end up on the new deploy too early (before being healthy). What would be a better way to do this at the kamal-proxy level? Or might it be considered to add "services as target" support or something like "service aliases with different settings" to kamal-proxy?
