### ISSUE TITLE
Setting custom headers based on the port

### ISSUE THREAD

**Issue by medius** [basecamp/kamal-proxy#25]
Is it currently, or will it be, possible to set custom headers on incoming requests for a specific port using Kamal Proxy?

For instance, I currently expose two ports, 80 and 443, using Traefik. There’s a load balancer in front of the application servers that handles TLS termination, directing HTTPS traffic to port 443 and HTTP traffic to port 80. In this setup, Traefik adds a custom header to the requests, allowing the Rails app to "AssumeSSL" for requests on port 443, while leaving port 80 requests as non-SSL.

Here's part of my deploy.yml config for application servers

```yaml
# Web (HTTP) endpoint
traefik.http.routers.myservice-web.entrypoints: web
# This is needed to prevent spoofing of X-Assume-Proto header on unencrypted requests
traefik.http.middlewares.no-ssl.headers.customrequestheaders.X-Assume-Proto: nope
traefik.http.routers.myservice-web.middlewares: no-ssl@docker

# Websecure (HTTPS) endpoint
traefik.http.routers.myservice-websecure.entrypoints: websecure
traefik.http.middlewares.assume-ssl.headers.customrequestheaders.X-Assume-Proto: https
traefik.http.routers.myservice-websecure.middlewares: assume-ssl@docker
```

and traefik
```yaml
traefik:
  options:
    publish:
      - "443:443"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
```

My rails application looks at "X-Assume-Proto" and assumes SSL if it's "http" and no SSL otherwise.

Being able to add/modify headers for the upstream servers seems like something that can be useful in many contexts. From what I understand, Kama Proxy does not support this yet. 

Or is there another way to pass on the information to the Rails app which port the original request came from?
