### ISSUE TITLE
TLS doesn't work: no viable challenge type found

### ISSUE THREAD

**Issue by a3kov** [basecamp/kamal-proxy#26]
I'm hosting an app on GCP using a free domain from DuckDNS. Ports 80 and 443 are open.
After successful deploy accessing the server on https:// doesn't work. The logs contain this:

```
2024-09-27T03:20:06.170255841Z {"time":"2024-09-27T03:20:06.169664821Z","level":"INFO","msg":"http: TLS handshake error from 1.2.3.4:47452: acme/autocert: unable to satisfy \"https://acme-v02.api.letsencrypt.org/acme/authz-v3/1111111111\" for domain \"mydomain.duckdns.org\": no viable challenge type found"}
```

Proxy config in deploy.yml
```
proxy:
  ssl: true
  app_port: 3000
  host: mydomain.duckdns.org,api.mydomain.duckdns.org
  healthcheck:
    path: /health
```
