### ISSUE TITLE
Kamal Proxy doesn't respect app_port

### ISSUE THREAD

**Issue by aarroisi** [basecamp/kamal-proxy#27]
I have config file like this:

```
...
proxy:
  host: <%= ENV['HOST_RULE'] %>
  app_port: 8001
  healthcheck:
    path: /api/test/
    interval: 5
    timeout: 12
...
```

But when I run `kamal deploy`, it shows an error like this:
`docker: Error response from daemon: container f0af1c4f712bdb6905f707cf2f7dc6f8981d9122372f0cbb1b2a9b1f6327f6fd: endpoint join on GW Network failed: driver failed programming external connectivity on endpoint gateway_53bcdfbd02e1 (19dacb3d01219d4f82dcfc1413fb5f8e69c9deca92ac025666daf779df40c7f0): failed to bind port 0.0.0.0:80/tcp: Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use.`

It seems like kamal-proxy still tries to bind to port 80, even though I specify it to run on port 8001.

I have tried many things:
- Adding to `env > clear > KAMAL_PROXY_HTTP_PORT: 8001`
- Running `export KAMAL_PROXY_HTTP_PORT=8001` before kamal deploy

Still tries to bind to port 80.
