### ISSUE TITLE
Redirects (302) seem to be swallowed in 0.8.0

### ISSUE THREAD

**Issue by julianrubisch** [basecamp/kamal-proxy#47]
I just upgraded an application to Kamal 2.2 (hence kamal-proxy 0.8.0) and observed some strange behavior concerning redirects:

After doing `kamal proxy reboot`, in both the kamal proxy as well as my application logs, I saw a 302 being rendered with the correct `Location` header.

In the browser, however, a 200 landed, but the `Location` header was preserved. I double and triple checked by moving between kamal 2.1.2 and kamal 2.2.0 and repeatedly doing `kamal proxy reboot`.

Additional context: it's an in-house app, hence no SSL. my kamal proxy config looks like this:

```yml
proxy:
  app_port: 3000
  ssl: false
  healthcheck:
    path: /health_check
    interval: 3
    timeout: 60
  forward_headers: true
```
